#!/bin/sh
#
# Start rk3326 linux service....
#

case "$1" in
	start)
		# Mount debugfs
		mount -t debugfs none /sys/kernel/debug

		# Power on wifi/bt if exist
		echo 1 >  /sys/class/rfkill/rfkill0/state || true

		# bluetooth
		rkbt /etc/bluetooth/broadcom/fw/bcm43438a0.hcd /dev/ttyS1 &

		# power manager
		/usr/bin/power_manager_service &

		# music
		/usr/bin/audioservice &

		#alsa conf
		CARD=rk817
		ALSA_CARD_NAME=rockchip_rk817-
		sed -i "4a${ALSA_CARD_NAME} cards.${CARD}" /usr/share/alsa/cards/aliases.conf

		echo performance > /sys/class/devfreq/ff400000.gpu/governor
		echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

		# ueventd
		/usr/bin/ueventd &
		;;
	stop)
		printf "stop finished"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0

