#!/bin/sh
#
# Start 3399 linux service....
#

case "$1" in
	start)
		# Mount debugfs
		mount -t debugfs none /sys/kernel/debug

		# Power on wifi/bt if exist
		echo 1 >  /sys/class/rfkill/rfkill0/state || true

		# bluetooth
		rkbt  /etc/bluetooth/bcm4354a1.hcd /dev/ttyS0 &

		# power manager
		/usr/bin/power_manager_service &

		# music
		/usr/bin/audioservice &

		echo performance > /sys/class/devfreq/ff9a0000.gpu/governor
		echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

		# ueventd
		/usr/bin/ueventd &
		;;
	stop)
		printf "stop finished"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0

