#!/bin/sh
#
# setup configfs for adbd and usb mass storage....
#

case "$1" in
start)
	mkdir /dev/usb-ffs -m 0770
	mkdir /dev/usb-ffs/adb -m 0770
	mount -t configfs none /sys/kernel/config
	mkdir /sys/kernel/config/usb_gadget/rockchip  -m 0770
	echo 0x2207 > /sys/kernel/config/usb_gadget/rockchip/idVendor
	echo 0x0006 > /sys/kernel/config/usb_gadget/rockchip/idProduct
	mkdir /sys/kernel/config/usb_gadget/rockchip/strings/0x409   -m 0770
	echo "0123456789ABCDEF" > /sys/kernel/config/usb_gadget/rockchip/strings/0x409/serialnumber
	echo "rockchip"  > /sys/kernel/config/usb_gadget/rockchip/strings/0x409/manufacturer
	echo "rk3xxx"  > /sys/kernel/config/usb_gadget/rockchip/strings/0x409/product
	mkdir /sys/kernel/config/usb_gadget/rockchip/configs/b.1  -m 0770              
	mkdir /sys/kernel/config/usb_gadget/rockchip/configs/b.1/strings/0x409  -m 0770
	echo 500 > /sys/kernel/config/usb_gadget/rockchip/configs/b.1/MaxPower

	mkdir /sys/kernel/config/usb_gadget/rockchip/functions/mass_storage.0
	echo /dev/disk/by-partlabel/userdata > /sys/kernel/config/usb_gadget/rockchip/functions/mass_storage.0/lun.0/file
	ln -s  /sys/kernel/config/usb_gadget/rockchip/functions/mass_storage.0 /sys/kernel/config/usb_gadget/rockchip/configs/b.1/f1

	mkdir /sys/kernel/config/usb_gadget/rockchip/functions/ffs.adb
	ln -s  /sys/kernel/config/usb_gadget/rockchip/functions/ffs.adb /sys/kernel/config/usb_gadget/rockchip/configs/b.1/f2
	echo "ums_adb" > /sys/kernel/config/usb_gadget/rockchip/configs/b.1/strings/0x409/configuration
	mount -t functionfs adb /dev/usb-ffs/adb

	export service_adb_tcp_port=5555
	adbd &
	sleep 1
	UDC=`ls /sys/class/udc/| awk '{print $1}'`
	echo $UDC > /sys/kernel/config/usb_gadget/rockchip/UDC

	;;
stop)
	echo "none" > /sys/kernel/config/usb_gadget/rockchip/UDC
	;;
restart|reload)
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
