#!/bin/sh
#
# Start 3288 linux service....
#

case "$1" in
	start)
		# Mount debugfs
		mount -t debugfs none /sys/kernel/debug

		# Power on wifi/bt if exist
		echo 1 >  /sys/class/rfkill/rfkill0/state || true

		# bluetooth
		rkbt  /etc/bluetooth/BCM4335C0.hcd /dev/ttyS0 &

		# power manager
		/usr/bin/power_manager_service &

		# music
		/usr/bin/audioservice &

		echo performance > /sys/class/devfreq/ffa30000.gpu/governor
		echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

		# create libmali.so link depend on chips type in the runtime
		GPU_VERSION=$(cat /sys/devices/platform/*gpu/gpuinfo)
		cd /usr/lib
		if [ "$GPU_VERSION" = 'Mali-T76x MP4 r1p0 0x0750' -o "$GPU_VERSION" = 'Mali-T76x 4 cores r1p0 0x0750' ];
		then
			#rk3288W, r1 version gpu chip
			ln -s libmali-midgard-t76x-r14p0-r1p0-wayland.so libmali.so
		else
			#rk3288, rk3288-C, rk3288-CG
			ln -s libmali-midgard-t76x-r14p0-r0p0-wayland.so libmali.so
		fi
		cd -

		# ueventd
		/usr/bin/ueventd &
		;;
	stop)
		printf "stop finished"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0

